-- SET10112 2018-9 TR2 001 - Formal Approaches to Software Engineering
-- Trident - Submarine Coursework
-- Version 0.3.1
-- Alexander Barker
-- 40333139
-- Last Updated on 19th April 2019
-- main.adb

with Trident; use Trident;
with Ada.Text_IO; use Ada.Text_IO;

procedure Main is
begin
   Put_Line("--------------------------------------------------------");
   Put_Line("        ___      _                   _                  ");
   Put_Line("       / __|_  _| |__ _ __  __ _ _ _(_)_ _  ___         ");
   Put_Line("       \__ \ || | '_ \ '  \/ _` | '_| | ' \/ -_)        ");
   Put_Line("       |___/\_,_|_.__/_|_|_\__,_|_| |_|_||_\___|        ");
   Put_Line("  ___         _           _   ___         _             ");
   Put_Line(" / __|___ _ _| |_ _ _ ___| | / __|_  _ __| |_ ___ _ __  ");
   Put_Line("| (__/ _ \ ' \  _| '_/ _ \ | \__ \ || (_-<  _/ -_) '  \ ");
   Put_Line(" \___\___/_||_\__|_| \___/_| |___/\_, /__/\__\___|_|_|_|");
   Put_Line("                                  |__/                  ");
   Put_Line("--------------------------------------------------------");
   Put_Line("Attempting to Start Submarine...");
   OperateSubmarine;
   Put("Is Nuclear Submarine Operational?: ");
   Put_Line(TridentSubmarine.operating'Image);
   Put("Is Weapons System Available?: ");
   WeaponsSystemCheck;
   Put_Line(TridentSubmarine.WeaponsAvailablity'Image);
   Put_Line("---------------------------------------------------");
   Put("Airlock Door One is: ");
   Put_Line(TridentSubmarine.CloseAirlockOne'Image);
   Put("Airlock Door Two is: ");
   Put_Line(TridentSubmarine.CloseAirlockTwo'Image);
   Put_Line("---------------------------------------------------");
   Put_Line("Attempting to Open both Doors...");
   OpenAirlockTwo;
   Put("Airlock Door One is: ");
   Put_Line(TridentSubmarine.CloseAirlockOne'Image);
   Put("Airlock Door Two is: ");
   Put_Line(TridentSubmarine.CloseAirlockTwo'Image);
   Put_Line("---------------------------------------------------");
   Put_Line("Closing Airlock Door One...");
   CloseAirlockOne;
   Put("Airlock Door One is: ");
   Put_Line(TridentSubmarine.CloseAirlockOne'Image);
   Put_Line("Closing Airlock Door Two...");
   CloseAirlockTwo;
   Put("Airlock Door Two is: ");
   Put_Line(TridentSubmarine.CloseAirlockTwo'Image);
   Put_Line("---------------------------------------------------");
   Put("Is Nuclear Submarine Operational?: ");
   OperateSubmarine;
   Put_Line(TridentSubmarine.operating'Image);
   Put("Is Weapons System Available?: ");
   WeaponsSystemCheck;
   Put_Line(TridentSubmarine.WeaponsAvailablity'Image);
   Put_Line("---------------------------------------------------");
   Put("Airlock Door one lock is: ");
   Put_Line(TridentSubmarine.LockAirlockOne'Image);
   Put("Airlock Door two lock is: ");
   Put_Line(TridentSubmarine.LockAirlockTwo'Image);
   Put_Line("---------------------------------------------------");
   Put_Line("Locking both Airlock Doors");
   LockAirlockOne;
   LockAirlockTwo;
   Put("Airlock Door One is: ");
   Put_Line(TridentSubmarine.LockAirlockOne'Image);
   Put("Airlock Door Two is: ");
   Put_Line(TridentSubmarine.LockAirlockTwo'Image);
   Put_Line("---------------------------------------------------");
   Put_Line("Attempting to Open Airlock Door One...");
   OpenAirlockOne;
   Put("Status of Airlock Door one: ");
   Put(TridentSubmarine.CloseAirlockOne'Image);
   Put(" and ");
   Put_Line(TridentSubmarine.LockAirlockOne'Image);
   Put_Line("Attempting to Open Airlock Door Two...");
   OpenAirlockTwo;
   Put("Status of Airlock Door Two: ");
   Put(TridentSubmarine.CloseAirlockTwo'Image);
   Put(" and ");
   Put_Line(TridentSubmarine.LockAirlockTwo'Image);
   Put_Line("---------------------------------------------------");
   Put("Is Nuclear Submarine Operational?: ");
   OperateSubmarine;
   Put_Line(TridentSubmarine.operating'Image);
   Put("Is Weapons System Available?: ");
   WeaponsSystemCheck;
   Put_Line(TridentSubmarine.WeaponsAvailablity'Image);
   Put_Line("---------------------------------------------------");
   Put("Is Weapons System Ready to Fire?: ");
   ReadyToFire;
   Put_Line(TridentSubmarine.loaded'Image);
   Put_Line("Attempting to Store Torpedoes...");
   Store;
   Put(TridentSubmarine.storedTorpedoes'Image);
   Put(" Torpedo: ");
   Put_Line(TridentSubmarine.torpedoes'Image);
   Store;
   Put(TridentSubmarine.storedTorpedoes'Image);
   Put(" Torpedo: ");
   Put_Line(TridentSubmarine.torpedoes'Image);
   Store;
   Put(TridentSubmarine.storedTorpedoes'Image);
   Put(" Torpedo: ");
   Put_Line(TridentSubmarine.torpedoes'Image);
   Store;
   Put(TridentSubmarine.storedTorpedoes'Image);
   Put(" Torpedo: ");
   Put_Line(TridentSubmarine.torpedoes'Image);
   Store;
   Put(TridentSubmarine.storedTorpedoes'Image);
   Put(" Torpedo: ");
   Put_Line(TridentSubmarine.torpedoes'Image);
   Store;
   Put(TridentSubmarine.storedTorpedoes'Image);
   Put(" Torpedo: ");
   Put_Line(TridentSubmarine.torpedoes'Image);
   Put_Line("---------------------------------------------------");
   Put("Is Weapons System Ready to Fire?: ");
   Put_Line(TridentSubmarine.loadedTorpedoes'Image);
   Put("Number of Torpedoes Stored: ");
   Put_Line(TridentSubmarine.torpedoes'Image);
   Put_Line("---------------------------------------------------");
   -- One;
   Put_Line("Attempting to Load Torpedo...");
   Load;
   Put("Loading Torpedo: ");
   Put_Line(TridentSubmarine.loaded'Image);
   Put_Line("Attempting to Fire Torpedo...");
   Put("Is Weapons System Ready to Fire?: ");
   Put_Line(TridentSubmarine.loadedTorpedoes'Image);
   Fire;
   Put(TridentSubmarine.firingTorpedoes'Image);
   Put(" Torpedo! Remaining ");
   Put_Line(TridentSubmarine.torpedoes'Image);
   Put_Line("---------------------------------------------------");
   -- Two;
   Put_Line("Attempting to Load Torpedo...");
   Load;
   Put("Loading Torpedo: ");
   Put_Line(TridentSubmarine.loaded'Image);
   Put_Line("Attempting to Fire Torpedo...");
   Put("Is Weapons System Ready to Fire?: ");
   Put_Line(TridentSubmarine.loadedTorpedoes'Image);
   Fire;
   Put(TridentSubmarine.firingTorpedoes'Image);
   Put(" Torpedo! Remaining ");
   Put_Line(TridentSubmarine.torpedoes'Image);
   Put_Line("---------------------------------------------------");
   -- Three;
   Put_Line("Attempting to Load Torpedo...");
   Load;
   Put("Loading Torpedo: ");
   Put_Line(TridentSubmarine.loaded'Image);
   Put_Line("Attempting to Fire Torpedo...");
   Put("Is Weapons System Ready to Fire?: ");
   Put_Line(TridentSubmarine.loadedTorpedoes'Image);
   Fire;
   Put(TridentSubmarine.firingTorpedoes'Image);
   Put(" Torpedo! Remaining ");
   Put_Line(TridentSubmarine.torpedoes'Image);
   Put_Line("---------------------------------------------------");
   -- Four;
   Put_Line("Attempting to Load Torpedo...");
   Load;
   Put("Loading Torpedo: ");
   Put_Line(TridentSubmarine.loaded'Image);
   Put_Line("Attempting to Fire Torpedo...");
   Put("Is Weapons System Ready to Fire?: ");
   Put_Line(TridentSubmarine.loadedTorpedoes'Image);
   Fire;
   Put(TridentSubmarine.firingTorpedoes'Image);
   Put(" Torpedo! Remaining ");
   Put_Line(TridentSubmarine.torpedoes'Image);
   Put_Line("---------------------------------------------------");
   -- Five;
   Put_Line("Attempting to Load Torpedo...");
   Load;
   Put("Loading Torpedo: ");
   Put_Line(TridentSubmarine.loaded'Image);
   Put_Line("Attempting to Fire Torpedo...");
   Put("Is Weapons System Ready to Fire?: ");
   Put_Line(TridentSubmarine.loadedTorpedoes'Image);
   Fire;
   Put(TridentSubmarine.firingTorpedoes'Image);
   Put(" Torpedo! Remaining ");
   Put_Line(TridentSubmarine.torpedoes'Image);
   Put_Line("---------------------------------------------------");
   -- Six;
   Put_Line("Attempting to Load Torpedo...");
   Load;
   Put("Loading Torpedo: ");
   Put_Line(TridentSubmarine.loaded'Image);
   Put_Line("Attempting to Fire Torpedo...");
   Put("Is Weapons System Ready to Fire?: ");
   Put_Line(TridentSubmarine.loadedTorpedoes'Image);
   Fire;
   Put(TridentSubmarine.firingTorpedoes'Image);
   Put(" Torpedo! Remaining ");
   Put_Line(TridentSubmarine.torpedoes'Image);
   Put_Line("---------------------------------------------------");
   Put_Line("Attempting to Dive!");
   Put("Depth Status: ");
   DepthPosition;
   Put_Line(TridentSubmarine.depthPositionCheck'Image);
   DepthTest;
   Put(TridentSubmarine.diveOperational'Image);
   Put(" at ");
   Put(TridentSubmarine.depthRange'Image);
   Put_Line(" metres...");
   Put_Line("---------------------------------------------------");
   DiveCheck;
   Put(TridentSubmarine.diveOperational'Image);
   Put(" from ");
   Put(TridentSubmarine.depthRange'Image);
   Put_Line(" metres...");
   Put("Depth Status: ");
   DepthPosition;
   Put_Line(TridentSubmarine.depthPositionCheck'Image);
   DepthTest;
   Put(TridentSubmarine.diveOperational'Image);
   Put(" from ");
   Put(TridentSubmarine.depthRange'Image);
   Put_Line(" metres...");
   Put("Depth Status: ");
   DepthPosition;
   Put_Line(TridentSubmarine.depthPositionCheck'Image);
   DepthTest;
   Put(TridentSubmarine.diveOperational'Image);
   Put(" from ");
   Put(TridentSubmarine.depthRange'Image);
   Put_Line(" metres...");
   Put("Depth Status: ");
   DepthPosition;
   Put_Line(TridentSubmarine.depthPositionCheck'Image);
   DepthTest;
   Put(TridentSubmarine.diveOperational'Image);
   Put(" from ");
   Put(TridentSubmarine.depthRange'Image);
   Put_Line(" metres...");
   Put("Depth Status: ");
   DepthPosition;
   Put_Line(TridentSubmarine.depthPositionCheck'Image);
   DepthTest;
   Put(TridentSubmarine.diveOperational'Image);
   Put(" from ");
   Put(TridentSubmarine.depthRange'Image);
   Put_Line(" metres...");
   Put("Depth Status: ");
   DepthPosition;
   Put_Line(TridentSubmarine.depthPositionCheck'Image);
   Put_Line("---------------------------------------------------");
   Put_Line("Resurfacing...");
   EmergencySurface;
   Put("Depth Status: ");
   DepthPosition;
   Put_Line(TridentSubmarine.depthPositionCheck'Image);
   DepthTest;
   Put(TridentSubmarine.diveOperational'Image);
   Put(" at ");
   Put(TridentSubmarine.depthRange'Image);
   Put_Line(" metres...");
   Put_Line("---------------------------------------------------");
   Put_Line("Attempting Life Support Check!");
   DiveCheck;
   Put("Life Support System: ");
   --100
   LifeSupportCheck;
   Put(TridentSubmarine.lifeSupportStatus'Image);
   Put(" - Oxygen Percentage: ");
   Put_Line(TridentSubmarine.oxygenRange'Image);
   Put("Life Support System: ");
   LifeSupportCheck;
   Put(TridentSubmarine.lifeSupportStatus'Image);
   OxygenTest;
   Put(" - Oxygen Percentage: ");
   Put_Line(TridentSubmarine.oxygenRange'Image);
   Put("Life Support System: ");
   --90
   LifeSupportCheck;
   Put(TridentSubmarine.lifeSupportStatus'Image);
   OxygenTest;
   Put(" - Oxygen Percentage: ");
   Put_Line(TridentSubmarine.oxygenRange'Image);
   Put("Life Support System: ");
   --80
   LifeSupportCheck;
   Put(TridentSubmarine.lifeSupportStatus'Image);
   OxygenTest;
   Put(" - Oxygen Percentage: ");
   Put_Line(TridentSubmarine.oxygenRange'Image);
   Put("Life Support System: ");
   --70
   LifeSupportCheck;
   Put(TridentSubmarine.lifeSupportStatus'Image);
   OxygenTest;
   Put(" - Oxygen Percentage: ");
   Put_Line(TridentSubmarine.oxygenRange'Image);
   Put("Life Support System: ");
   --60
   LifeSupportCheck;
   Put(TridentSubmarine.lifeSupportStatus'Image);
   OxygenTest;
   Put(" - Oxygen Percentage: ");
   Put_Line(TridentSubmarine.oxygenRange'Image);
   Put("Life Support System: ");
   --50
   LifeSupportCheck;
   Put(TridentSubmarine.lifeSupportStatus'Image);
   OxygenTest;
   Put(" - Oxygen Percentage: ");
   Put_Line(TridentSubmarine.oxygenRange'Image);
   Put("Life Support System: ");
   --40
   LifeSupportCheck;
   Put(TridentSubmarine.lifeSupportStatus'Image);
   OxygenTest;
   Put(" - Oxygen Percentage: ");
   Put_Line(TridentSubmarine.oxygenRange'Image);
   Put("Life Support System: ");
   --30
   LifeSupportCheck;
   Put(TridentSubmarine.lifeSupportStatus'Image);
   OxygenTest;
   Put(" - Oxygen Percentage: ");
   Put_Line(TridentSubmarine.oxygenRange'Image);
   Put("Life Support System: ");
   --20
   LifeSupportCheck;
   Put(TridentSubmarine.lifeSupportStatus'Image);
   OxygenTest;
   Put(" - Oxygen Percentage: ");
   Put_Line(TridentSubmarine.oxygenRange'Image);
   Put("Life Support System: ");
   --10
   LifeSupportCheck;
   Put(TridentSubmarine.lifeSupportStatus'Image);
   OxygenTest;
   Put(" - Oxygen Percentage: ");
   Put_Line(TridentSubmarine.oxygenRange'Image);
   Put("Life Support System: ");
   --0
   LifeSupportCheck;
   Put(TridentSubmarine.lifeSupportStatus'Image);
   OxygenTest;
   Put(" - Oxygen Percentage: ");
   Put_Line(TridentSubmarine.oxygenRange'Image);
   LifeSupportCheck;
   Put_Line(TridentSubmarine.lifeSupportStatus'Image);
   Put_Line("---------------------------------------------------");
   Put_Line("Attempting Reactor Temperature Check!");
   DiveCheck;
   ReactorCheck;
   Put_Line("---------------------------------------------------");

end Main;
